name: Docker

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag commentsvetting:$(date +%s)
